### ISSUE TITLE
Robot doesn't move

### ISSUE THREAD

**Issue by Vineet-Pandey** [lprobsth/gazebo_ros_tracked_vehicle_interface#6]
Thanks for Creating this plugin interface!
I am working with this package and I am able to see the gazebo topic publishing on ``` ~/cmd_vel_twist ``` in gazebo (as shown in the screen grab), however the robot doesn't move. Should I use additional controllers or packages to work with this? Could you please provide some insight into how the twist inputs from this plug-in interface goes to the ``` SimpleTrackedVehiclePlugin ``` 
![Screenshot from 2022-12-09 12-07-24](https://user-images.githubusercontent.com/29963970/206756079-e8f1eb02-7222-43cb-920a-c2f3b64c4148.png)

**Comment by lprobsth** [comment]
Hey,

it looks like there is no namespace present in this gazebo topic.

A good starting point would be to look at the gazebo topics and see if the `SimpleTrackedVehiclePlugin` has subscribed to the right topic.
```
# list topics
gz topic -l
# get topic info
gz topic -i /gazebo/[world name]/[model name]/cmd_vel_twist
```

One workaround would be to set the ignition (=gazebo) topic explicitly to the namespaced topic:

```
[...]
     <commandIGNTopic>/gazebo/[world name]/[model name]/cmd_vel_twist</commandIGNTopic>
[...]
```

**Comment by Vineet-Pandey** [comment]
It was an issue with the namespace in the gazebo topic. Closing this issue.
